version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: postgres_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydb
    volumes:
      - .:/app
      - ./src/sql:/docker-entrypoint-initb.d
    command: ["python", "src/scripts/app.py"]

volumes:
  db_data:

